<?php

/**
 * PluginEavGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEavGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEavGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEavGroups');
    }
}