<?php

/**
 * PluginEavValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEavValuesTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object PluginEavValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEavValues');
    }

    /**
     * delete eav be resource id and entity id
     *
     * @param int $destination_ressource_id identifiant de la ressource
     * @param int $destination_entity_id    identifiant de l'entité
     *
     * @return int
     */
    public static function deleteByRessourceIdAndEntityId($ressource_id, $entity_id)
    {
        return Doctrine_Query::create()
                ->delete()
                ->from("EavValues")
                ->where(sprintf("ressource_id = '%s'", $ressource_id))
                ->andWhere(sprintf("entity_id = '%s'", $entity_id))
                ->execute();
    }

}