<?php

/**
 * PluginEavFullValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEavFullValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEavFullValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEavFullValues');
    }
}