<?php

/**
 * actions.class.php
 *
 * PHP version 5
 *
 * @category Actions
 * @package  Eav
 * @author   ALI Hichem <ali.hichem@mail.com>
 */

/**
 * eavActions
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @category Actions
 * @package  Eav
 * @author   ALI Hichem <ali.hichem@mail.com>
 */
class eavActions extends sfActions
{

    /**
     * SaveJson action
     *
     * @param sfRequest $request A request object
     *
     * @return void
     */
    public function executeSaveJson(sfWebRequest $request)
    {
        return sfView::NONE;
    }

    /**
     * LoadJson action
     *
     * @param sfRequest $request A request object
     *
     * @return void
     */
    public function executeLoadJson(sfWebRequest $request)
    {
        $user = $this->getUser();
        $json = $request->getParameter('amp;ul','');
        if($json != '')
        {
            $formData['form_structure'] = serialize($json);
        }
        else
        {
            $ressource_id = $request->getParameter('ressource_id');
            $entity_id = $request->getParameter('entity_id');
            $formStructure = EavTable::buildFormStructure($ressource_id, $entity_id);
            $formData['form_structure'] = serialize($formStructure);
        }
        
        $formData['form_hash'] = sha1($formData['form_structure']);
        $form = new Formbuilder($formData);
        $form->render_xml();
        exit;
    }

    /**
     * Load EAV html structure
     *
     * @param sfRequest $request A request object
     *
     * @return string html structure
     */
    public function executeLoadStructure(sfWebRequest $request)
    {
        $vars = array("source_ressource_id" => $request->getParameter("source_ressource_id"),
            "source_entity_id" => $request->getParameter("source_entity_id"),
            "destination_ressource_id" => $request->getParameter("destination_ressource_id"),
            "destination_entity_id" => $request->getParameter("destination_entity_id"));
        return $this->renderComponent("eav", "render", $vars);
    }

}