# sfEntityAttributeValuePlugin - resource file 


EavGroups:
  id: 1
Eav:
  id: 2
EavFullValues:
  id: 3
EavValues:
  id: 4
sfGuardGroup:
  id: 5
sfGuardPermission:
  id: 6
sfGuardGroupPermission:
  id: 7
sfGuardUser:
  id: 8
sfGuardUserPermission:
  id: 9
sfGuardUserGroup:
  id: 10
sfGuardRememberKey:
  id: 11
sfGuardForgotPassword:
  id: 12
Teams:
  id: 13
Groups:
  id: 14
Members:
  id: 15